// Generated by CoffeeScript 1.6.3
/*
* funciones utilizada en investigador_map para agregar valores 

investigador_map = function (k, v) {
  log("inv in");
  var ms = 1000;
  var started = new Date().getTime();
  while((new Date().getTime() - started) < ms) {
  }
  emit("llave", v*v);
  log("inv in out");
};

investigador_reduce = function (k, vals) {
  var total = vals.reduce(function(a, b) {
    return parseInt(a) + parseInt(b);
  });
  return total;
};

investigador_map = (k, v) -> 
  log "imap con #{k}, #{v}"
  ms = 1000
  started = new Date().getTime()
  while((new Date().getTime() - started) < ms)
    ;
  
  emit "llave", v * v
  log "inv in out"
*/


(function() {
  var Cola, cola, emit, error, log, result,
    __slice = [].slice;

  result = [];

  log = function() {
    var msg, others;
    msg = arguments[0], others = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return console.log.apply(console, ["[Worker] " + msg].concat(__slice.call(others)));
  };

  error = function(msg) {
    return console.error("[Worker] " + msg);
  };

  emit = function(key, val) {
    log("emit con " + key + " " + val);
    return result.push([key, val]);
  };

  Cola = (function() {
    /*
    Se encarga de realizar las llamadas a `map` cuidando de no utilizar
    el máximo de los recursos del cliente.
    */

    function Cola(map) {
      this.map = map;
      this.i = 0;
      this._data = null;
      this._keys = null;
      this.executing = false;
      this.sleeping = true;
      this._tout = null;
    }

    Cola.prototype._process = function() {
      /*
      Procesa un elemento de @_data y se espera una ventana de tiempo para
      seguir ejecutando la siguiente
      */

      var _this = this;
      if (this.executing || this.sleeping) {
        return;
      }
      log("@_process " + this.executing + " " + this.sleeping);
      this.executing = true;
      if (this.i < this._keys.length) {
        log("ejecutando map con " + this._keys[this.i] + " y " + this._data[this._keys[this.i]]);
        this.map(this._keys[this.i], this._data[this._keys[this.i]]);
        this.i++;
      } else {
        log("termino de procesar");
        this._sendResult();
      }
      if (!this.sleeping) {
        this._tout = setTimeout(function() {
          log("desde el timeout");
          return _this._process();
        }, 50);
      }
      return this.executing = false;
    };

    Cola.prototype._initData = function() {
      log("init data");
      this._keys = null;
      this._data = null;
      return this.i = 0;
    };

    Cola.prototype._sendResult = function() {
      var _result;
      this.sleep();
      _result = [];
      result.forEach(function(item) {
        return _result.push(item.slice());
      });
      log("_sendResult", result);
      return postMessage({
        type: "send_result",
        args: JSON.stringify(result)
      });
    };

    Cola.prototype.setData = function(data) {
      result = [];
      this.i = 0;
      this._data = data;
      return this._keys = Object.keys(data);
    };

    Cola.prototype.wake = function() {
      log("wake");
      if (!this.sleeping) {
        return;
      }
      this.sleeping = false;
      return this._process();
    };

    Cola.prototype.sleep = function() {
      log("sleep");
      clearTimeout(this._tout);
      return this.sleeping = true;
    };

    return Cola;

  })();

  cola = new Cola(investigador_map);

  this.onmessage = function(evnt) {
    var msg;
    msg = evnt.data;
    switch (msg.type) {
      case "start":
        if (!msg.args) {
          error("Datos invalidos:", msg.args);
          return;
        }
        log("start", msg.args);
        cola.setData(msg.args);
        return cola.wake();
      case "pause":
        log("pause recv");
        return cola.sleep();
      case "resume":
        log("resumign recv");
        return cola.wake();
    }
  };

  this.postMessage({
    type: "ready"
  });

}).call(this);
