// Generated by CoffeeScript 1.4.0
(function() {
  var exports;

  exports = module.exports = function(app, mongoose) {
    var workerSchema;
    workerSchema = new mongoose.Schema({
      imap: String,
      ireduce: String,
      map_results: {
        type: mongoose.Schema.Types.Mixed,
        "default": {}
      },
      reduce_data: {
        type: mongoose.Schema.Types.Mixed,
        "default": {}
      },
      reduce_results: {
        type: mongoose.Schema.Types.Mixed,
        "default": {}
      },
      available_slices: {
        type: [Number],
        "default": []
      },
      slices: {
        type: [mongoose.Schema.Types.Mixed],
        "default": []
      },
      user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
      },
      enabled_to_process: Boolean
    }, {
      minimize: false
    });
    return mongoose.model('Worker', workerSchema);
  };

}).call(this);
