// Generated by CoffeeScript 1.4.0
(function() {
  var exports;

  exports = module.exports = function(app, mongoose) {
    var workerSchema;
    workerSchema = new mongoose.Schema({
      data: mongoose.Schema.Types.Mixed,
      imap: String,
      ireduce: String,
      map_results: mongoose.Schema.Types.Mixed,
      reduce_data: mongoose.Schema.Types.Mixed,
      reduce_results: mongoose.Schema.Types.Mixed,
      result: mongoose.Schema.Types.Mixed,
      available_slices: [Number],
      slices: [mongoose.Schema.Types.Mixed]
    });
    return mongoose.model('Worker', workerSchema);
  };

}).call(this);
