// Generated by CoffeeScript 1.4.0
(function() {
  var MongoClient, ObjectID, app, assert, bodyParser, db, db_url, express, methodOverride, models, mongoose, morgan, _;

  express = require('express.io');

  bodyParser = require('body-parser');

  morgan = require('morgan');

  assert = require('assert');

  MongoClient = require('mongodb').MongoClient;

  ObjectID = require('mongodb').ObjectID;

  _ = require("underscore");

  methodOverride = require('method-override');

  mongoose = require('mongoose');

  app = express();

  db_url = 'mongodb://127.0.0.1:27017/tesis';

  db = null;

  mongoose.connect(db_url, function(err, connection) {
    assert.ifError(err);
    console.log(connection);
    return assert.ok(connection);
  });

  models = require('./models/worker')(app, mongoose);

  app.use(morgan('default'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.listen('8080');

}).call(this);
